version: '3'
services:
    bankservice_web:
        # Path to dockerfile.
        # '.' represents the current directory in which
        # docker-compose.yml is present.
        build: .
        
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - bankservice_web
        ports:
            - "4000:4000"
networks:
    default:
        driver: bridge
        name: bankservice_web
    # Mapping of container port to host
    
    #ports:
    #  - "8761"
    # Mount volume 
    #volumes:
    #  - "/usercode/:/code"
    
    # Link database container to app container 
    # for reachability.
    #links:
    #  - "database:backenddb"
    
  #database:

    # image to fetch from docker hub
   # image: mysql/mysql-server:5.7

    # Environment variables for startup script
    # container will use these variables
    # to start the container with these define variables. 
   # environment:
    #  - "MYSQL_ROOT_PASSWORD=root"
    #  - "MYSQL_USER=testuser"
    #  - "MYSQL_PASSWORD=admin123"
    # - "MYSQL_DATABASE=backend"
    # Mount init.sql file to automatically run 
    # and create tables for us.
